version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm i
      - run: echo "lint"
      - run: CI=true npm run lint
  test:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "npm installing" # encho = printout
      - run: npm i
      - run: echo "jest-ci"
      - run: CI=true npm run jest-ci # example:CI=true inject env variable CI = true
workflows:
  version: 2
  lint: # workflow name
    jobs:
      - lint
